CREATE TABLE person.revinfo
(
    rev      INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    revtstmp BIGINT,
    CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
);

CREATE TABLE person.users_aud
(
    id          UUID    NOT NULL,
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    secret_key  VARCHAR(32),
    first_name  VARCHAR(32),
    last_name   VARCHAR(32),
    verified_at TIMESTAMP WITHOUT TIME ZONE,
    archived_at TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(64),
    address_id  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(255),
    CONSTRAINT users_aud_pkey PRIMARY KEY (id, rev),
    CONSTRAINT users_aud_rev_fk FOREIGN KEY (rev) REFERENCES person.revinfo (rev)
);

CREATE TABLE person.individuals_aud
(
    id              UUID    NOT NULL,
    rev             INTEGER NOT NULL,
    revtype         SMALLINT,
    user_id         UUID,
    passport_number VARCHAR(32),
    phone_number    VARCHAR(32),
    email           VARCHAR(32),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    CONSTRAINT individuals_aud_pkey PRIMARY KEY (id, rev),
    CONSTRAINT individuals_aud_rev_fk FOREIGN KEY (rev) REFERENCES person.revinfo (rev)
);

CREATE TABLE person.countries_aud
(
    id         BIGINT  NOT NULL,
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    name       VARCHAR(255),
    alpha2     VARCHAR(2),
    alpha3     VARCHAR(3),
    status     VARCHAR(64),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    CONSTRAINT countries_aud_pkey PRIMARY KEY (id, rev),
    CONSTRAINT countries_aud_rev_fk FOREIGN KEY (rev) REFERENCES person.revinfo (rev)
); 